#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRManagement")]
	public partial class HR_ManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDocumentUpload(DocumentUpload instance);
    partial void UpdateDocumentUpload(DocumentUpload instance);
    partial void DeleteDocumentUpload(DocumentUpload instance);
    #endregion
		
		public HR_ManagementDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["constr"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HR_ManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HR_ManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HR_ManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HR_ManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DocumentUpload> DocumentUploads
		{
			get
			{
				return this.GetTable<DocumentUpload>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentUpload_Insert")]
		public int DocumentUpload_Insert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lastname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string dob, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotoName", DbType="NVarChar(50)")] string photoName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotoType", DbType="NVarChar(50)")] string photoType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary photo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string x10Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string x10Type, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="X10", DbType="VarBinary(MAX)")] System.Data.Linq.Binary x10, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string x12Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string x12Type, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="X12", DbType="VarBinary(MAX)")] System.Data.Linq.Binary x12, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GraName", DbType="NVarChar(50)")] string graName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GraType", DbType="NVarChar(50)")] string graType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary graduation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeeName", DbType="NVarChar(50)")] string deeName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeeType", DbType="NVarChar(50)")] string deeType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary degree, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostName", DbType="NVarChar(50)")] string postName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostType", DbType="NVarChar(50)")] string postType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary postgraduation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AadharName", DbType="NVarChar(50)")] string aadharName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AadharType", DbType="NVarChar(50)")] string aadharType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary aadharcard, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PanName", DbType="NVarChar(50)")] string panName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PanType", DbType="NVarChar(50)")] string panType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary pancard, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankName", DbType="NVarChar(50)")] string bankName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankType", DbType="NVarChar(50)")] string bankType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary bankpass, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count", DbType="Int")] ref System.Nullable<int> count)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lastname, dob, photoName, photoType, photo, gender, email, x10Name, x10Type, x10, x12Name, x12Type, x12, graName, graType, graduation, deeName, deeType, degree, postName, postType, postgraduation, aadharName, aadharType, aadharcard, panName, panType, pancard, bankName, bankType, bankpass, count);
			count = ((System.Nullable<int>)(result.GetParameterValue(32)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocumentUpload")]
	public partial class DocumentUpload : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _fname;
		
		private string _lastname;
		
		private string _dob;
		
		private string _PhotoName;
		
		private string _PhotoType;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _gender;
		
		private string _email;
		
		private string _x10Name;
		
		private string _X10Type;
		
		private System.Data.Linq.Binary _X10;
		
		private string _x12Name;
		
		private string _X12Type;
		
		private System.Data.Linq.Binary _X12;
		
		private string _GraName;
		
		private string _GraType;
		
		private System.Data.Linq.Binary _graduation;
		
		private string _DeeName;
		
		private string _DeeType;
		
		private System.Data.Linq.Binary _Degree;
		
		private string _PostName;
		
		private string _PostType;
		
		private System.Data.Linq.Binary _Postgraduation;
		
		private string _AadharName;
		
		private string _AadharType;
		
		private System.Data.Linq.Binary _Aadharcard;
		
		private string _PanName;
		
		private string _PanType;
		
		private System.Data.Linq.Binary _pancard;
		
		private string _BankName;
		
		private string _BankType;
		
		private System.Data.Linq.Binary _Bankpass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OndobChanging(string value);
    partial void OndobChanged();
    partial void OnPhotoNameChanging(string value);
    partial void OnPhotoNameChanged();
    partial void OnPhotoTypeChanging(string value);
    partial void OnPhotoTypeChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onx10NameChanging(string value);
    partial void Onx10NameChanged();
    partial void OnX10TypeChanging(string value);
    partial void OnX10TypeChanged();
    partial void OnX10Changing(System.Data.Linq.Binary value);
    partial void OnX10Changed();
    partial void Onx12NameChanging(string value);
    partial void Onx12NameChanged();
    partial void OnX12TypeChanging(string value);
    partial void OnX12TypeChanged();
    partial void OnX12Changing(System.Data.Linq.Binary value);
    partial void OnX12Changed();
    partial void OnGraNameChanging(string value);
    partial void OnGraNameChanged();
    partial void OnGraTypeChanging(string value);
    partial void OnGraTypeChanged();
    partial void OngraduationChanging(System.Data.Linq.Binary value);
    partial void OngraduationChanged();
    partial void OnDeeNameChanging(string value);
    partial void OnDeeNameChanged();
    partial void OnDeeTypeChanging(string value);
    partial void OnDeeTypeChanged();
    partial void OnDegreeChanging(System.Data.Linq.Binary value);
    partial void OnDegreeChanged();
    partial void OnPostNameChanging(string value);
    partial void OnPostNameChanged();
    partial void OnPostTypeChanging(string value);
    partial void OnPostTypeChanged();
    partial void OnPostgraduationChanging(System.Data.Linq.Binary value);
    partial void OnPostgraduationChanged();
    partial void OnAadharNameChanging(string value);
    partial void OnAadharNameChanged();
    partial void OnAadharTypeChanging(string value);
    partial void OnAadharTypeChanged();
    partial void OnAadharcardChanging(System.Data.Linq.Binary value);
    partial void OnAadharcardChanged();
    partial void OnPanNameChanging(string value);
    partial void OnPanNameChanged();
    partial void OnPanTypeChanging(string value);
    partial void OnPanTypeChanged();
    partial void OnpancardChanging(System.Data.Linq.Binary value);
    partial void OnpancardChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBankTypeChanging(string value);
    partial void OnBankTypeChanged();
    partial void OnBankpassChanging(System.Data.Linq.Binary value);
    partial void OnBankpassChanged();
    #endregion
		
		public DocumentUpload()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this.OnfnameChanging(value);
					this.SendPropertyChanging();
					this._fname = value;
					this.SendPropertyChanged("fname");
					this.OnfnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="NVarChar(50)")]
		public string dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoName", DbType="NVarChar(50)")]
		public string PhotoName
		{
			get
			{
				return this._PhotoName;
			}
			set
			{
				if ((this._PhotoName != value))
				{
					this.OnPhotoNameChanging(value);
					this.SendPropertyChanging();
					this._PhotoName = value;
					this.SendPropertyChanged("PhotoName");
					this.OnPhotoNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoType", DbType="NVarChar(50)")]
		public string PhotoType
		{
			get
			{
				return this._PhotoType;
			}
			set
			{
				if ((this._PhotoType != value))
				{
					this.OnPhotoTypeChanging(value);
					this.SendPropertyChanging();
					this._PhotoType = value;
					this.SendPropertyChanged("PhotoType");
					this.OnPhotoTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x10Name", DbType="NVarChar(50)")]
		public string x10Name
		{
			get
			{
				return this._x10Name;
			}
			set
			{
				if ((this._x10Name != value))
				{
					this.Onx10NameChanging(value);
					this.SendPropertyChanging();
					this._x10Name = value;
					this.SendPropertyChanged("x10Name");
					this.Onx10NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X10Type", DbType="NVarChar(50)")]
		public string X10Type
		{
			get
			{
				return this._X10Type;
			}
			set
			{
				if ((this._X10Type != value))
				{
					this.OnX10TypeChanging(value);
					this.SendPropertyChanging();
					this._X10Type = value;
					this.SendPropertyChanged("X10Type");
					this.OnX10TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X10", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary X10
		{
			get
			{
				return this._X10;
			}
			set
			{
				if ((this._X10 != value))
				{
					this.OnX10Changing(value);
					this.SendPropertyChanging();
					this._X10 = value;
					this.SendPropertyChanged("X10");
					this.OnX10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x12Name", DbType="NVarChar(50)")]
		public string x12Name
		{
			get
			{
				return this._x12Name;
			}
			set
			{
				if ((this._x12Name != value))
				{
					this.Onx12NameChanging(value);
					this.SendPropertyChanging();
					this._x12Name = value;
					this.SendPropertyChanged("x12Name");
					this.Onx12NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X12Type", DbType="NVarChar(50)")]
		public string X12Type
		{
			get
			{
				return this._X12Type;
			}
			set
			{
				if ((this._X12Type != value))
				{
					this.OnX12TypeChanging(value);
					this.SendPropertyChanging();
					this._X12Type = value;
					this.SendPropertyChanged("X12Type");
					this.OnX12TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X12", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary X12
		{
			get
			{
				return this._X12;
			}
			set
			{
				if ((this._X12 != value))
				{
					this.OnX12Changing(value);
					this.SendPropertyChanging();
					this._X12 = value;
					this.SendPropertyChanged("X12");
					this.OnX12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GraName", DbType="NVarChar(50)")]
		public string GraName
		{
			get
			{
				return this._GraName;
			}
			set
			{
				if ((this._GraName != value))
				{
					this.OnGraNameChanging(value);
					this.SendPropertyChanging();
					this._GraName = value;
					this.SendPropertyChanged("GraName");
					this.OnGraNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GraType", DbType="NVarChar(50)")]
		public string GraType
		{
			get
			{
				return this._GraType;
			}
			set
			{
				if ((this._GraType != value))
				{
					this.OnGraTypeChanging(value);
					this.SendPropertyChanging();
					this._GraType = value;
					this.SendPropertyChanged("GraType");
					this.OnGraTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_graduation", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary graduation
		{
			get
			{
				return this._graduation;
			}
			set
			{
				if ((this._graduation != value))
				{
					this.OngraduationChanging(value);
					this.SendPropertyChanging();
					this._graduation = value;
					this.SendPropertyChanged("graduation");
					this.OngraduationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeeName", DbType="NVarChar(50)")]
		public string DeeName
		{
			get
			{
				return this._DeeName;
			}
			set
			{
				if ((this._DeeName != value))
				{
					this.OnDeeNameChanging(value);
					this.SendPropertyChanging();
					this._DeeName = value;
					this.SendPropertyChanged("DeeName");
					this.OnDeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeeType", DbType="NVarChar(50)")]
		public string DeeType
		{
			get
			{
				return this._DeeType;
			}
			set
			{
				if ((this._DeeType != value))
				{
					this.OnDeeTypeChanging(value);
					this.SendPropertyChanging();
					this._DeeType = value;
					this.SendPropertyChanged("DeeType");
					this.OnDeeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degree", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Degree
		{
			get
			{
				return this._Degree;
			}
			set
			{
				if ((this._Degree != value))
				{
					this.OnDegreeChanging(value);
					this.SendPropertyChanging();
					this._Degree = value;
					this.SendPropertyChanged("Degree");
					this.OnDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostName", DbType="NVarChar(50)")]
		public string PostName
		{
			get
			{
				return this._PostName;
			}
			set
			{
				if ((this._PostName != value))
				{
					this.OnPostNameChanging(value);
					this.SendPropertyChanging();
					this._PostName = value;
					this.SendPropertyChanged("PostName");
					this.OnPostNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostType", DbType="NVarChar(50)")]
		public string PostType
		{
			get
			{
				return this._PostType;
			}
			set
			{
				if ((this._PostType != value))
				{
					this.OnPostTypeChanging(value);
					this.SendPropertyChanging();
					this._PostType = value;
					this.SendPropertyChanged("PostType");
					this.OnPostTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postgraduation", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Postgraduation
		{
			get
			{
				return this._Postgraduation;
			}
			set
			{
				if ((this._Postgraduation != value))
				{
					this.OnPostgraduationChanging(value);
					this.SendPropertyChanging();
					this._Postgraduation = value;
					this.SendPropertyChanged("Postgraduation");
					this.OnPostgraduationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadharName", DbType="NVarChar(50)")]
		public string AadharName
		{
			get
			{
				return this._AadharName;
			}
			set
			{
				if ((this._AadharName != value))
				{
					this.OnAadharNameChanging(value);
					this.SendPropertyChanging();
					this._AadharName = value;
					this.SendPropertyChanged("AadharName");
					this.OnAadharNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadharType", DbType="NVarChar(50)")]
		public string AadharType
		{
			get
			{
				return this._AadharType;
			}
			set
			{
				if ((this._AadharType != value))
				{
					this.OnAadharTypeChanging(value);
					this.SendPropertyChanging();
					this._AadharType = value;
					this.SendPropertyChanged("AadharType");
					this.OnAadharTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aadharcard", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Aadharcard
		{
			get
			{
				return this._Aadharcard;
			}
			set
			{
				if ((this._Aadharcard != value))
				{
					this.OnAadharcardChanging(value);
					this.SendPropertyChanging();
					this._Aadharcard = value;
					this.SendPropertyChanged("Aadharcard");
					this.OnAadharcardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanName", DbType="NVarChar(50)")]
		public string PanName
		{
			get
			{
				return this._PanName;
			}
			set
			{
				if ((this._PanName != value))
				{
					this.OnPanNameChanging(value);
					this.SendPropertyChanging();
					this._PanName = value;
					this.SendPropertyChanged("PanName");
					this.OnPanNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanType", DbType="NVarChar(50)")]
		public string PanType
		{
			get
			{
				return this._PanType;
			}
			set
			{
				if ((this._PanType != value))
				{
					this.OnPanTypeChanging(value);
					this.SendPropertyChanging();
					this._PanType = value;
					this.SendPropertyChanged("PanType");
					this.OnPanTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pancard", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary pancard
		{
			get
			{
				return this._pancard;
			}
			set
			{
				if ((this._pancard != value))
				{
					this.OnpancardChanging(value);
					this.SendPropertyChanging();
					this._pancard = value;
					this.SendPropertyChanged("pancard");
					this.OnpancardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(50)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankType", DbType="NVarChar(50)")]
		public string BankType
		{
			get
			{
				return this._BankType;
			}
			set
			{
				if ((this._BankType != value))
				{
					this.OnBankTypeChanging(value);
					this.SendPropertyChanging();
					this._BankType = value;
					this.SendPropertyChanged("BankType");
					this.OnBankTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bankpass", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Bankpass
		{
			get
			{
				return this._Bankpass;
			}
			set
			{
				if ((this._Bankpass != value))
				{
					this.OnBankpassChanging(value);
					this.SendPropertyChanging();
					this._Bankpass = value;
					this.SendPropertyChanged("Bankpass");
					this.OnBankpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
